server:
  port: 8082

---

spring:
  application:
    name: server3

  kafka:
    consumer:
      bootstrap-servers: steach.ssafy.io:29092
      group-id: group-id-oing
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: steach.ssafy.io:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    template:
      default-topic: dev-topic

---

test:
  project:
    topic: dev-topic

